
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    {type: 'autogenerated', dirName: '.'}
  ],


  // Sidebar for EVE Wormhole Mapper
  /*
  docs : [
    {
      type: "category",
			label: "Getting Started",
			link: {
				type: 'generated-index',
				title: 'Getting Started',
				slug: '/category/getting-started',
				keywords: ['start'],
				image: '/img/docusaurus.png',
				},
			items: [
				"GettingStarted/installation",
				"Notes/updates"
			],
    }
  ]*/
};

export default sidebars;
